[project]
name = "todo-htmx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.4",
]

[dependency-groups]
dev = [
    "model-bakery>=1.20.5",
    "pytest-django>=4.11.1",
]
